### ISSUE TITLE
Missing !

### ISSUE THREAD

**Issue by passsy** [dkrutskikh/actions-toolkit-dart#26]
`issueFileCommand` throws when the file exists. It should throw when it doesn't exist!

https://github.com/dkrutskikh/actions-toolkit-dart/blob/594a1fd9b855bcad884cdf2e01baec0548f50215/lib/src/core/file_command.dart#L15-L17

**Comment by dkrutskikh** [comment]
@passsy good catch! Fixed in 0.5.0 version. I'll close this issue, fell free to reopen if problem not fully fixed.
