### ISSUE TITLE
exportVariable: Using `/` instead of `\n` as separator

### ISSUE THREAD

**Issue by passsy** [dkrutskikh/actions-toolkit-dart#27]
I was comparing the [js](https://github.com/actions/toolkit/blob/00282d61458d99f725588a9463b9d25dfda51c22/packages/core/src/core.ts#L83-L95) implementation with the dart implementation here. js uses `os.EOL` but dart uses `p.context.separator` instead. Those are not identical!

https://github.com/dkrutskikh/actions-toolkit-dart/blob/594a1fd9b855bcad884cdf2e01baec0548f50215/lib/src/core/core.dart#L22

Please replace it with 

```dart
final eol = Platform.isWindows ? '\r\n' : '\n';
```

**Comment by dkrutskikh** [comment]
@passsy fixed in 0.5.1
